Осуществим предобработку данных с Твиттера, чтобы отчищенный данные в дальнейшем использовать для задачи классификации. Данный датасет содержит негативные (label = 1) и нейтральные (label = 0) высказывания.
Для работы объединим train_df и test_df.

Задания:

1) Удалим @user из всех твитов с помощью паттерна "@[\w]*". Для этого создадим функцию: 
 - для того, чтобы найти все вхождения паттерна в тексте, необходимо использовать re.findall(pattern, input_txt)
 - для для замены @user на пробел, необходимо использовать re.sub()

2) Изменим регистр твитов на нижний с помощью .lower().

3) Заменим сокращения с апострофами (пример: ain't, can't) на пробел, используя apostrophe_dict. Для этого необходимо сделать функцию: для каждого слова в тексте проверить (for word in text.split()), если слово есть в словаре apostrophe_dict в качестве ключа (сокращенного слова), то заменить ключ на значение (полную версию слова).

4) Заменим сокращения на их полные формы, используя short_word_dict. Для этого воспользуемся функцией, используемой в предыдущем пункте.

5) Заменим эмотиконы (пример: ":)" = "happy") на пробелы, используя emoticon_dict. Для этого воспользуемся функцией, используемой в предыдущем пункте.

6) Заменим пунктуацию на пробелы, используя re.sub() и паттерн r'[^\w\s]'.

7) Заменим спец. символы на пробелы, используя re.sub() и паттерн r'[^a-zA-Z0-9]'.

8) Заменим числа на пробелы, используя re.sub() и паттерн r'[^a-zA-Z]'.

9) Удалим из текста слова длиной в 1 символ, используя ' '.join([w for w in x.split() if len(w)>1]).

10) Поделим твиты на токены с помощью nltk.tokenize.word_tokenize, создав новый столбец 'tweet_token'.

11) Удалим стоп-слова из токенов, используя nltk.corpus.stopwords. Создадим столбец 'tweet_token_filtered' без стоп-слов.

12) Применим стемминг к токенам с помощью nltk.stem.PorterStemmer. Создадим столбец 'tweet_stemmed' после применения стемминга.

13) Применим лемматизацию к токенам с помощью nltk.stem.wordnet.WordNetLemmatizer. Создадим столбец 'tweet_lemmatized' после применения лемматизации.

14) Сохраним результат предобработки в pickle-файл.

In [1]:
apostrophe_dict = {
"ain't": "am not / are not",
"aren't": "are not / am not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he had / he would",
"he'd've": "he would have",
"he'll": "he shall / he will",
"he'll've": "he shall have / he will have",
"he's": "he has / he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how has / how is",
"i'd": "I had / I would",
"i'd've": "I would have",
"i'll": "I shall / I will",
"i'll've": "I shall have / I will have",
"i'm": "I am",
"i've": "I have",
"isn't": "is not",
"it'd": "it had / it would",
"it'd've": "it would have",
"it'll": "it shall / it will",
"it'll've": "it shall have / it will have",
"it's": "it has / it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she had / she would",
"she'd've": "she would have",
"she'll": "she shall / she will",
"she'll've": "she shall have / she will have",
"she's": "she has / she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as / so is",
"that'd": "that would / that had",
"that'd've": "that would have",
"that's": "that has / that is",
"there'd": "there had / there would",
"there'd've": "there would have",
"there's": "there has / there is",
"they'd": "they had / they would",
"they'd've": "they would have",
"they'll": "they shall / they will",
"they'll've": "they shall have / they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we had / we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what shall / what will",
"what'll've": "what shall have / what will have",
"what're": "what are",
"what's": "what has / what is",
"what've": "what have",
"when's": "when has / when is",
"when've": "when have",
"where'd": "where did",
"where's": "where has / where is",
"where've": "where have",
"who'll": "who shall / who will",
"who'll've": "who shall have / who will have",
"who's": "who has / who is",
"who've": "who have",
"why's": "why has / why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you had / you would",
"you'd've": "you would have",
"you'll": "you shall / you will",
"you'll've": "you shall have / you will have",
"you're": "you are",
"you've": "you have"
}



short_word_dict = {
"121": "one to one",
"a/s/l": "age, sex, location",
"adn": "any day now",
"afaik": "as far as I know",
"afk": "away from keyboard",
"aight": "alright",
"alol": "actually laughing out loud",
"b4": "before",
"b4n": "bye for now",
"bak": "back at the keyboard",
"bf": "boyfriend",
"bff": "best friends forever",
"bfn": "bye for now",
"bg": "big grin",
"bta": "but then again",
"btw": "by the way",
"cid": "crying in disgrace",
"cnp": "continued in my next post",
"cp": "chat post",
"cu": "see you",
"cul": "see you later",
"cul8r": "see you later",
"cya": "bye",
"cyo": "see you online",
"dbau": "doing business as usual",
"fud": "fear, uncertainty, and doubt",
"fwiw": "for what it's worth",
"fyi": "for your information",
"g": "grin",
"g2g": "got to go",
"ga": "go ahead",
"gal": "get a life",
"gf": "girlfriend",
"gfn": "gone for now",
"gmbo": "giggling my butt off",
"gmta": "great minds think alike",
"h8": "hate",
"hagn": "have a good night",
"hdop": "help delete online predators",
"hhis": "hanging head in shame",
"iac": "in any case",
"ianal": "I am not a lawyer",
"ic": "I see",
"idk": "I don't know",
"imao": "in my arrogant opinion",
"imnsho": "in my not so humble opinion",
"imo": "in my opinion",
"iow": "in other words",
"ipn": "I’m posting naked",
"irl": "in real life",
"jk": "just kidding",
"l8r": "later",
"ld": "later, dude",
"ldr": "long distance relationship",
"llta": "lots and lots of thunderous applause",
"lmao": "laugh my ass off",
"lmirl": "let's meet in real life",
"lol": "laugh out loud",
"ltr": "longterm relationship",
"lulab": "love you like a brother",
"lulas": "love you like a sister",
"luv": "love",
"m/f": "male or female",
"m8": "mate",
"milf": "mother I would like to fuck",
"oll": "online love",
"omg": "oh my god",
"otoh": "on the other hand",
"pir": "parent in room",
"ppl": "people",
"r": "are",
"rofl": "roll on the floor laughing",
"rpg": "role playing games",
"ru": "are you",
"shid": "slaps head in disgust",
"somy": "sick of me yet",
"sot": "short of time",
"thanx": "thanks",
"thx": "thanks",
"ttyl": "talk to you later",
"u": "you",
"ur": "you are",
"uw": "you’re welcome",
"wb": "welcome back",
"wfm": "works for me",
"wibni": "wouldn't it be nice if",
"wtf": "what the fuck",
"wtg": "way to go",
"wtgp": "want to go private",
"ym": "young man",
"gr8": "great"
}


emoticon_dict = {
":)": "happy",
":‑)": "happy",
":-]": "happy",
":-3": "happy",
":->": "happy",
"8-)": "happy",
":-}": "happy",
":o)": "happy",
":c)": "happy",
":^)": "happy",
"=]": "happy",
"=)": "happy",
"<3": "happy",
":-(": "sad",
":(": "sad",
":c": "sad",
":<": "sad",
":[": "sad",
">:[": "sad",
":{": "sad",
">:(": "sad",
":-c": "sad",
":-< ": "sad",
":-[": "sad",
":-||": "sad"
}

In [2]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
import os

In [3]:
train_df = pd.read_csv('train_tweets.csv')
train_df.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [4]:
test_df = pd.read_csv('test_tweets.csv')
test_df.head()

      id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [5]:
combine_df = train_df.append(test_df, ignore_index = True, sort = False)
combine_df.head()

   id  label                                              tweet
0   1    0.0   @user when a father is dysfunctional and is s...
1   2    0.0  @user @user thanks for #lyft credit i can't us...
2   3    0.0                                bihday your majesty
3   4    0.0  #model   i love u take with u all the time in ...
4   5    0.0             factsguide: society now    #motivation

In [6]:
print(combine_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49159 entries, 0 to 49158
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      49159 non-null  int64
 1   label   31962 non-null  float64
 2   tweet   49159 non-null  object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB
None

In [7]:
combine_df.head(20)

    id  label                                              tweet
0    1    0.0   @user when a father is dysfunctional and is s...
1    2    0.0  @user @user thanks for #lyft credit i can't us...
2    3    0.0                                bihday your majesty
3    4    0.0  #model   i love u take with u all the time in ...
4    5    0.0             factsguide: society now    #motivation
5    6    0.0  [2/2] huge fan fare and big talking before the...
6    7    0.0   @user camping tomorrow @user @user @user @use...
7    8    0.0  the next school year is the year for exams.ð...
8    9    0.0  we won!!! love the land!!! #allin #cavs #champ...
9   10    0.0   @user @user welcome here !  i'm   it's so #gr...
10  11    0.0   â #ireland consumer price index (mom) climb...
11  12    0.0  we are so selfish. #orlando #standwithorlando ...
12  13    0.0  i get to see my daddy today!!   #80days #getti...
13  14    1.0  @user #cnn calls #michigan middle school 'buil...
14  15    1.0  no comment!  in #australia   #opkillingbay #se...
15  16    0.0  ouch...junior is angryð#got7 #junior #yugyo...
16  17    0.0  i am thankful for having a paner. #thankful #p...
17  18    1.0                             retweet if you agree!
18  19    0.0  its #friday! ð smiles all around via ig use...
19  20    0.0  as we all know, essential oils are not made of...

1. Удалим @user из всех твитов с помощью паттерна "@[\w]*". Для этого создадим функцию: 
 - для того, чтобы найти все вхождения паттерна в тексте, необходимо использовать re.findall(pattern, input_txt)
 - для для замены @user на пробел, необходимо использовать re.sub()

In [8]:
def del_user(tweet):
  tweet = re.sub("@[\w]*", " ", tweet)
  return tweet

combine_df['tweet'] = combine_df['tweet'].apply(del_user)
combine_df.head()

   id  label                                              tweet
0   1    0.0     when a father is dysfunctional and is so se...
1   2    0.0      thanks for #lyft credit i can't use cause ...
2   3    0.0                                bihday your majesty
3   4    0.0  #model   i love u take with u all the time in ...
4   5    0.0             factsguide: society now    #motivation

2. Изменим регистр твитов на нижний с помощью .lower()

In [9]:
combine_df['tweet'] = combine_df['tweet'].apply(lambda x: x.lower())
combine_df['tweet'].head()

0       when a father is dysfunctional and is so se...
1        thanks for #lyft credit i can't use cause ...
2                                  bihday your majesty
3    #model   i love u take with u all the time in ...
4               factsguide: society now    #motivation
Name: tweet, dtype: object

3. Заменим сокращения с апострофами (пример: ain't, can't) на пробел, используя apostrophe_dict. Для этого необходимо сделать функцию: для каждого слова в тексте проверить (for word in text.split()), если слово есть в словаре apostrophe_dict в качестве ключа (сокращенного слова), то заменить ключ на значение (полную версию слова).

In [10]:
def change_contraction(tweet):
  tweet = tweet.split()
  for i, word in enumerate(tweet):
    if word in apostrophe_dict.keys():
      tweet[i] = apostrophe_dict[word]
  tweet = ' '.join(tweet)
  return tweet
combine_df['tweet'] = combine_df['tweet'].apply(change_contraction)
combine_df.head()

   id  label                                              tweet
0   1    0.0  when a father is dysfunctional and is so selfi...
1   2    0.0  thanks for #lyft credit i cannot use cause the...
2   3    0.0                                bihday your majesty
3   4    0.0  #model i love u take with u all the time in ur...
4   5    0.0                factsguide: society now #motivation

4. Заменим сокращения на их полные формы, используя short_word_dict. Для этого воспользуемся функцией, используемой в предыдущем пункте.

In [11]:
def change_shorts(tweet):
  tweet = tweet.split()
  for i, word in enumerate(tweet):
    if word in short_word_dict.keys():
      tweet[i] =short_word_dict[word]
  tweet = ' '.join(tweet)
  return tweet
combine_df['tweet'] = combine_df['tweet'].apply(change_shorts)
combine_df.head()

   id  label                                              tweet
0   1    0.0  when a father is dysfunctional and is so selfi...
1   2    0.0  thanks for #lyft credit i cannot use cause the...
2   3    0.0                                bihday your majesty
3   4    0.0  #model i love you take with you all the time i...
4   5    0.0                factsguide: society now #motivation

5. Заменим эмотиконы (пример: ":)" = "happy") на пробелы, используя emoticon_dict. Для этого воспользуемся функцией, используемой в предыдущем пункте.

In [12]:
def change_emoticon(tweet):
  tweet = tweet.split()
  for i, word in enumerate(tweet):
    if word in emoticon_dict.keys():
      tweet[i] = emoticon_dict[word]
  tweet = ' '.join(tweet)
  return tweet
combine_df['tweet'] = combine_df['tweet'].apply(change_emoticon)
combine_df.head()

   id  label                                              tweet
0   1    0.0  when a father is dysfunctional and is so selfi...
1   2    0.0  thanks for #lyft credit i cannot use cause the...
2   3    0.0                                bihday your majesty
3   4    0.0  #model i love you take with you all the time i...
4   5    0.0                factsguide: society now #motivation

6. Заменим пунктуацию на пробелы, используя re.sub() и паттерн r'[^\w\s]'

In [13]:
def del_signs(tweet):
  tweet = re.sub("[^\w\s]", " ", tweet)
  return tweet

combine_df['tweet'] = combine_df['tweet'].apply(del_signs)
combine_df.head()

   id  label                                              tweet
0   1    0.0  when a father is dysfunctional and is so selfi...
1   2    0.0  thanks for  lyft credit i cannot use cause the...
2   3    0.0                                bihday your majesty
3   4    0.0   model i love you take with you all the time i...
4   5    0.0                factsguide  society now  motivation

7. Заменим спец. символы на пробелы, используя re.sub() и паттерн r'[^a-zA-Z0-9]'

In [14]:
def del_symbols(tweet):
  tweet = re.sub("[^a-zA-Z0-9]", " ", tweet)
  return tweet

combine_df['tweet'] = combine_df['tweet'].apply(del_symbols)
combine_df.head()

   id  label                                              tweet
0   1    0.0  when a father is dysfunctional and is so selfi...
1   2    0.0  thanks for  lyft credit i cannot use cause the...
2   3    0.0                                bihday your majesty
3   4    0.0   model i love you take with you all the time i...
4   5    0.0                factsguide  society now  motivation

8. Заменим числа на пробелы, используя re.sub() и паттерн r'[^a-zA-Z]'

In [15]:
def del_dig(tweet):
  tweet = re.sub("[^a-zA-Z]", " ", tweet)
  return tweet

combine_df['tweet'] = combine_df['tweet'].apply(del_dig)
combine_df.head()

   id  label                                              tweet
0   1    0.0  when a father is dysfunctional and is so selfi...
1   2    0.0  thanks for  lyft credit i cannot use cause the...
2   3    0.0                                bihday your majesty
3   4    0.0   model i love you take with you all the time i...
4   5    0.0                factsguide  society now  motivation

9. Удалим из текста слова длиной в 1 символ, используя ' '.join([w for w in x.split() if len(w)>1])

In [16]:
def del_words(tweet):
  return ' '.join([w for w in tweet.split() if len(w)>1])

combine_df['tweet'] = combine_df['tweet'].apply(del_words)
combine_df.head()

   id  label                                              tweet
0   1    0.0  when father is dysfunctional and is so selfish...
1   2    0.0  thanks for lyft credit cannot use cause they d...
2   3    0.0                                bihday your majesty
3   4    0.0    model love you take with you all the time in ur
4   5    0.0                  factsguide society now motivation

10. Поделим твиты на токены с помощью nltk.tokenize.word_tokenize, создав новый столбец 'tweet_token'.

In [17]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [18]:
combine_df['tweet_token'] = combine_df['tweet'].apply(nltk.tokenize.word_tokenize)
combine_df.head()

,id,label,tweet,tweet_token
0,1,0.0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,..."
1,2,0.0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau..."
2,3,0.0,bihday your majesty,"[bihday, your, majesty]"
3,4,0.0,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ..."
4,5,0.0,factsguide society now motivation,"[factsguide, society, now, motivation]"

11. Удалим стоп-слова из токенов, используя nltk.corpus.stopwords. Создадим столбец 'tweet_token_filtered' без стоп-слов.

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
stop_words = set(nltk.corpus.stopwords.words("english"))

combine_df['tweet_token_filtered'] = combine_df['tweet_token'].apply(lambda words: [word for word in words if not word in stop_words])
combine_df.head()

,id,label,tweet,tweet_token,tweet_token_filtered
0,1,0.0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ..."
1,2,0.0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee..."
2,3,0.0,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]"
3,4,0.0,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, ur]"
4,5,0.0,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]"

12. Применим стемминг к токенам с помощью nltk.stem.PorterStemmer. Создадим столбец 'tweet_stemmed' после применения стемминга.

In [21]:
stemmer = nltk.stem.PorterStemmer()

combine_df['tweet_stemmed'] = combine_df['tweet_token_filtered'].apply(lambda x:  [stemmer.stem(i) for i in x] )
combine_df.head()

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed
0,1,0.0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc..."
1,2,0.0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc..."
2,3,0.0,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]"
3,4,0.0,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, ur]","[model, love, take, time, ur]"
4,5,0.0,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]"

13. Применим лемматизацию к токенам с помощью nltk.stem.wordnet.WordNetLemmatizer. Создадим столбец 'tweet_lemmatized' после применения лемматизации.

In [22]:
from nltk.corpus import wordnet
nltk.download('wordnet')
  

lemmatizer = nltk.stem.wordnet.WordNetLemmatizer()

combine_df['tweet_lemmatized'] = combine_df['tweet_token_filtered'].apply(lambda x:  [lemmatizer.lemmatize(i, wordnet.VERB) for i in x] )
combine_df.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunctional, selfish, drag, kid, dy..."
1,2,0.0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thank, lyft, credit, use, cause, offer, wheel..."
2,3,0.0,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesty]"
3,4,0.0,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, ur]","[model, love, take, time, ur]","[model, love, take, time, ur]"
4,5,0.0,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]","[factsguide, society, motivation]"

14. Сохраним результат предобработки в pickle-файл.

In [24]:
import pickle

with open('dump.dat', 'wb') as dump_out:
    pickle.dump(combine_df, dump_out)